# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: alacritty
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8
  #window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  #dimensions:
  #  columns: 0
  #  lines: 0
  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  #padding:
  #  x: 0
  #  y: 0
  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  #decorations: full
  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  #startup_mode: Windowed
  # Window title
  #title: Alacritty
  # Window class (Linux/BSD only):
  #class:
  # Application instance name
  #instance: Alacritty
  # General application class
  #general: Alacritty
  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  #gtk_theme_variant: None
  #scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  #history: 10000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  #multiplier: 3
  # https://github.com/alacritty/alacritty/issues/3549 --
  WINIT_X11_SCALE_FACTOR: "1"

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Hack Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Hack Nerd Font
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Hack Nerd Font
    # Style can be specified to pick a specific face.
    # style: Italic
  size: 8.0

# transparent --
# https://wiki.gentoo.org/wiki/Alacritty
#background_opacity: 0.8 # value range is 0 ~ 1
# update -> see below
# https://github.com/alacritty/alacritty/issues/168
window:
  decorations: none
  opacity: 0.8

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false
# github Alacritty Colors
# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '#292C3E'
    foreground: '#EBEBEB'

  # Cursor colors
  cursor:
    text: '#FF261E'
    cursor: '#FF261E'

  # Normal colors
  normal:
    black: '#0d0d0d'
    red: '#FF301B'
    green: '#A0E521'
    yellow: '#FFC620'
    blue: '#1BA6FA'
    magenta: '#8763B8'
    cyan: '#21DEEF'
    white: '#EBEBEB'

  # Bright colors
  bright:
    black: '#6D7070'
    red: '#FF4352'
    green: '#B8E466'
    yellow: '#FFD750'
    blue: '#1BA6FA'
    magenta: '#A578EA'
    cyan: '#73FBF1'
    white: '#FEFEF8'
